

spring:
  rabbitmq:
    host: localhost    #\u4E3B\u673A\u5730\u5740
    port: 5672         #\u7AEF\u53E3\u53F7
    username: guest    #\u7528\u6237\u540D
    password: guest    #\u5BC6\u7801
    virtual-host: /    #\u865A\u62DF\u4E3B\u673A\u8DEF\u5F84
server:
  port: 8001