server:
  port: 6001

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bigbaibaibai/XiaoHuiBook-Config.git  #github上面仓库的http的uri